notifications:
  email: false

dist: xenial

language: c
compiler: gcc
cache: ccache

addons:
  apt:
    packages:
      - autopoint
      - docbook-simple
      - docbook-xsl
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls-dev
      - libgpgme11-dev
      - libgss-dev
      - libidn2-0-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.2-dev
      - libnotmuch-dev
      - libqdbm-dev
      - libsasl2-dev
      - libslang2-dev
      - libssl-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - lua5.2
      - lynx
      - python-pip
      - python-software-properties
      - xsltproc

git:
  depth: 3

before_install:
  - pip install --user cpp-coveralls

install:
  - git clone --depth 1 https://github.com/neomutt/travis-build.git ~/config

before_script:
  - ccache --zero-stats
  - export ANSI_CLEAR
  - export -f travis_fold
  - export -f travis_nanoseconds
  - export -f travis_time_finish
  - export -f travis_time_start

script:
  - ./configure --disable-doc --testing --coverage --everything && make && make test 

after_success:
  - coveralls --gcov-options '\-lp' --build-root . --include mutt --include email --include address --include config

after_script:
  - ccache --show-stats

